

spring.datasource.url=jdbc:postgresql://db.uthiqaamfyfecpfjpkxj.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Thiagoandrade1.
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

